# CMake generated Testfile for 
# Source directory: /Users/arcop/code/git/libmysofa-wasm
# Build directory: /Users/arcop/code/git/libmysofa-wasm/build-ninja-debug
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(Mesh2HRTF "src/mysofa2json" "-c" "/Users/arcop/code/git/libmysofa-wasm/tests/Mesh2HRTF.sofa")
set_tests_properties(Mesh2HRTF PROPERTIES  _BACKTRACE_TRIPLES "/Users/arcop/code/git/libmysofa-wasm/CMakeLists.txt;66;add_test;/Users/arcop/code/git/libmysofa-wasm/CMakeLists.txt;0;")
add_test(D1_48K_24bit_0.3s_FIR_SOFA "src/mysofa2json" "/Users/arcop/code/git/libmysofa-wasm/tests/D1_48K_24bit_0.3s_FIR_SOFA.sofa")
set_tests_properties(D1_48K_24bit_0.3s_FIR_SOFA PROPERTIES  _BACKTRACE_TRIPLES "/Users/arcop/code/git/libmysofa-wasm/CMakeLists.txt;68;add_test;/Users/arcop/code/git/libmysofa-wasm/CMakeLists.txt;0;")
add_test(H20_44K_16bit_256tap_FIR_SOFA "/Users/arcop/code/git/libmysofa-wasm/tests/compareIgnoreNew.sh" "/Users/arcop/code/git/libmysofa-wasm/tests/H20_44K_16bit_256tap_FIR_SOFA")
set_tests_properties(H20_44K_16bit_256tap_FIR_SOFA PROPERTIES  _BACKTRACE_TRIPLES "/Users/arcop/code/git/libmysofa-wasm/CMakeLists.txt;70;add_test;/Users/arcop/code/git/libmysofa-wasm/CMakeLists.txt;0;")
add_test(MIT_KEMAR_large_pinna "/Users/arcop/code/git/libmysofa-wasm/tests/compare.sh" "/Users/arcop/code/git/libmysofa-wasm/tests/MIT_KEMAR_large_pinna")
set_tests_properties(MIT_KEMAR_large_pinna PROPERTIES  _BACKTRACE_TRIPLES "/Users/arcop/code/git/libmysofa-wasm/CMakeLists.txt;72;add_test;/Users/arcop/code/git/libmysofa-wasm/CMakeLists.txt;0;")
add_test(MIT_KEMAR_normal_pinna "/Users/arcop/code/git/libmysofa-wasm/tests/compareIgnoreNew.sh" "/Users/arcop/code/git/libmysofa-wasm/tests/MIT_KEMAR_normal_pinna")
set_tests_properties(MIT_KEMAR_normal_pinna PROPERTIES  _BACKTRACE_TRIPLES "/Users/arcop/code/git/libmysofa-wasm/CMakeLists.txt;74;add_test;/Users/arcop/code/git/libmysofa-wasm/CMakeLists.txt;0;")
add_test(MIT_KEMAR_normal_pinna.old "/Users/arcop/code/git/libmysofa-wasm/tests/compare.sh" "/Users/arcop/code/git/libmysofa-wasm/tests/MIT_KEMAR_normal_pinna.old")
set_tests_properties(MIT_KEMAR_normal_pinna.old PROPERTIES  _BACKTRACE_TRIPLES "/Users/arcop/code/git/libmysofa-wasm/CMakeLists.txt;76;add_test;/Users/arcop/code/git/libmysofa-wasm/CMakeLists.txt;0;")
add_test(dtf_nh2 "/Users/arcop/code/git/libmysofa-wasm/tests/compareIgnoreNew.sh" "/Users/arcop/code/git/libmysofa-wasm/tests/dtf_nh2")
set_tests_properties(dtf_nh2 PROPERTIES  _BACKTRACE_TRIPLES "/Users/arcop/code/git/libmysofa-wasm/CMakeLists.txt;78;add_test;/Users/arcop/code/git/libmysofa-wasm/CMakeLists.txt;0;")
add_test(hrtf_c_nh898 "/Users/arcop/code/git/libmysofa-wasm/tests/compareIgnoreNew.sh" "/Users/arcop/code/git/libmysofa-wasm/tests/hrtf_c_nh898")
set_tests_properties(hrtf_c_nh898 PROPERTIES  _BACKTRACE_TRIPLES "/Users/arcop/code/git/libmysofa-wasm/CMakeLists.txt;80;add_test;/Users/arcop/code/git/libmysofa-wasm/CMakeLists.txt;0;")
add_test(fail-issue-72 "/Users/arcop/code/git/libmysofa-wasm/tests/notcrashed.sh" "/Users/arcop/code/git/libmysofa-wasm/tests/fail-issue-72")
set_tests_properties(fail-issue-72 PROPERTIES  _BACKTRACE_TRIPLES "/Users/arcop/code/git/libmysofa-wasm/CMakeLists.txt;107;add_test;/Users/arcop/code/git/libmysofa-wasm/CMakeLists.txt;0;")
add_test(fail-issue-75 "/Users/arcop/code/git/libmysofa-wasm/tests/notcrashed.sh" "/Users/arcop/code/git/libmysofa-wasm/tests/fail-issue-75")
set_tests_properties(fail-issue-75 PROPERTIES  _BACKTRACE_TRIPLES "/Users/arcop/code/git/libmysofa-wasm/CMakeLists.txt;107;add_test;/Users/arcop/code/git/libmysofa-wasm/CMakeLists.txt;0;")
add_test(fail-issue-76 "/Users/arcop/code/git/libmysofa-wasm/tests/notcrashed.sh" "/Users/arcop/code/git/libmysofa-wasm/tests/fail-issue-76")
set_tests_properties(fail-issue-76 PROPERTIES  _BACKTRACE_TRIPLES "/Users/arcop/code/git/libmysofa-wasm/CMakeLists.txt;107;add_test;/Users/arcop/code/git/libmysofa-wasm/CMakeLists.txt;0;")
add_test(fail-issue-77 "/Users/arcop/code/git/libmysofa-wasm/tests/notcrashed.sh" "/Users/arcop/code/git/libmysofa-wasm/tests/fail-issue-77")
set_tests_properties(fail-issue-77 PROPERTIES  _BACKTRACE_TRIPLES "/Users/arcop/code/git/libmysofa-wasm/CMakeLists.txt;107;add_test;/Users/arcop/code/git/libmysofa-wasm/CMakeLists.txt;0;")
add_test(fail-issue-79 "/Users/arcop/code/git/libmysofa-wasm/tests/notcrashed.sh" "/Users/arcop/code/git/libmysofa-wasm/tests/fail-issue-79")
set_tests_properties(fail-issue-79 PROPERTIES  _BACKTRACE_TRIPLES "/Users/arcop/code/git/libmysofa-wasm/CMakeLists.txt;107;add_test;/Users/arcop/code/git/libmysofa-wasm/CMakeLists.txt;0;")
add_test(fail-issue-82 "/Users/arcop/code/git/libmysofa-wasm/tests/notcrashed.sh" "/Users/arcop/code/git/libmysofa-wasm/tests/fail-issue-82")
set_tests_properties(fail-issue-82 PROPERTIES  _BACKTRACE_TRIPLES "/Users/arcop/code/git/libmysofa-wasm/CMakeLists.txt;107;add_test;/Users/arcop/code/git/libmysofa-wasm/CMakeLists.txt;0;")
add_test(fail-issue-83 "/Users/arcop/code/git/libmysofa-wasm/tests/notcrashed.sh" "/Users/arcop/code/git/libmysofa-wasm/tests/fail-issue-83")
set_tests_properties(fail-issue-83 PROPERTIES  _BACKTRACE_TRIPLES "/Users/arcop/code/git/libmysofa-wasm/CMakeLists.txt;107;add_test;/Users/arcop/code/git/libmysofa-wasm/CMakeLists.txt;0;")
add_test(fail-issue-84 "/Users/arcop/code/git/libmysofa-wasm/tests/notcrashed.sh" "/Users/arcop/code/git/libmysofa-wasm/tests/fail-issue-84")
set_tests_properties(fail-issue-84 PROPERTIES  _BACKTRACE_TRIPLES "/Users/arcop/code/git/libmysofa-wasm/CMakeLists.txt;107;add_test;/Users/arcop/code/git/libmysofa-wasm/CMakeLists.txt;0;")
add_test(fail-issue-130 "/Users/arcop/code/git/libmysofa-wasm/tests/notcrashed.sh" "/Users/arcop/code/git/libmysofa-wasm/tests/fail-issue-130")
set_tests_properties(fail-issue-130 PROPERTIES  _BACKTRACE_TRIPLES "/Users/arcop/code/git/libmysofa-wasm/CMakeLists.txt;107;add_test;/Users/arcop/code/git/libmysofa-wasm/CMakeLists.txt;0;")
add_test(fail-issue-132 "/Users/arcop/code/git/libmysofa-wasm/tests/notcrashed.sh" "/Users/arcop/code/git/libmysofa-wasm/tests/fail-issue-132")
set_tests_properties(fail-issue-132 PROPERTIES  _BACKTRACE_TRIPLES "/Users/arcop/code/git/libmysofa-wasm/CMakeLists.txt;107;add_test;/Users/arcop/code/git/libmysofa-wasm/CMakeLists.txt;0;")
add_test(fail-issue-135 "/Users/arcop/code/git/libmysofa-wasm/tests/notcrashed.sh" "/Users/arcop/code/git/libmysofa-wasm/tests/fail-issue-135")
set_tests_properties(fail-issue-135 PROPERTIES  _BACKTRACE_TRIPLES "/Users/arcop/code/git/libmysofa-wasm/CMakeLists.txt;107;add_test;/Users/arcop/code/git/libmysofa-wasm/CMakeLists.txt;0;")
add_test(fail-issue-136 "/Users/arcop/code/git/libmysofa-wasm/tests/notcrashed.sh" "/Users/arcop/code/git/libmysofa-wasm/tests/fail-issue-136")
set_tests_properties(fail-issue-136 PROPERTIES  _BACKTRACE_TRIPLES "/Users/arcop/code/git/libmysofa-wasm/CMakeLists.txt;107;add_test;/Users/arcop/code/git/libmysofa-wasm/CMakeLists.txt;0;")
add_test(fail-issue-137 "/Users/arcop/code/git/libmysofa-wasm/tests/notcrashed.sh" "/Users/arcop/code/git/libmysofa-wasm/tests/fail-issue-137")
set_tests_properties(fail-issue-137 PROPERTIES  _BACKTRACE_TRIPLES "/Users/arcop/code/git/libmysofa-wasm/CMakeLists.txt;107;add_test;/Users/arcop/code/git/libmysofa-wasm/CMakeLists.txt;0;")
add_test(fail-issue-138 "/Users/arcop/code/git/libmysofa-wasm/tests/notcrashed.sh" "/Users/arcop/code/git/libmysofa-wasm/tests/fail-issue-138")
set_tests_properties(fail-issue-138 PROPERTIES  _BACKTRACE_TRIPLES "/Users/arcop/code/git/libmysofa-wasm/CMakeLists.txt;107;add_test;/Users/arcop/code/git/libmysofa-wasm/CMakeLists.txt;0;")
add_test(fail-issue-156 "/Users/arcop/code/git/libmysofa-wasm/tests/notcrashed.sh" "/Users/arcop/code/git/libmysofa-wasm/tests/fail-issue-156")
set_tests_properties(fail-issue-156 PROPERTIES  _BACKTRACE_TRIPLES "/Users/arcop/code/git/libmysofa-wasm/CMakeLists.txt;107;add_test;/Users/arcop/code/git/libmysofa-wasm/CMakeLists.txt;0;")
add_test(fail-issue-163 "/Users/arcop/code/git/libmysofa-wasm/tests/notcrashed.sh" "/Users/arcop/code/git/libmysofa-wasm/tests/fail-issue-163")
set_tests_properties(fail-issue-163 PROPERTIES  _BACKTRACE_TRIPLES "/Users/arcop/code/git/libmysofa-wasm/CMakeLists.txt;107;add_test;/Users/arcop/code/git/libmysofa-wasm/CMakeLists.txt;0;")
add_test(fail-issue-167a "/Users/arcop/code/git/libmysofa-wasm/tests/notcrashed.sh" "/Users/arcop/code/git/libmysofa-wasm/tests/fail-issue-167a")
set_tests_properties(fail-issue-167a PROPERTIES  _BACKTRACE_TRIPLES "/Users/arcop/code/git/libmysofa-wasm/CMakeLists.txt;107;add_test;/Users/arcop/code/git/libmysofa-wasm/CMakeLists.txt;0;")
add_test(fail-issue-167b "/Users/arcop/code/git/libmysofa-wasm/tests/notcrashed.sh" "/Users/arcop/code/git/libmysofa-wasm/tests/fail-issue-167b")
set_tests_properties(fail-issue-167b PROPERTIES  _BACKTRACE_TRIPLES "/Users/arcop/code/git/libmysofa-wasm/CMakeLists.txt;107;add_test;/Users/arcop/code/git/libmysofa-wasm/CMakeLists.txt;0;")
add_test(fail-issue-168 "/Users/arcop/code/git/libmysofa-wasm/tests/notcrashed.sh" "/Users/arcop/code/git/libmysofa-wasm/tests/fail-issue-168")
set_tests_properties(fail-issue-168 PROPERTIES  _BACKTRACE_TRIPLES "/Users/arcop/code/git/libmysofa-wasm/CMakeLists.txt;107;add_test;/Users/arcop/code/git/libmysofa-wasm/CMakeLists.txt;0;")
add_test(fail-issue-171 "/Users/arcop/code/git/libmysofa-wasm/tests/notcrashed.sh" "/Users/arcop/code/git/libmysofa-wasm/tests/fail-issue-171")
set_tests_properties(fail-issue-171 PROPERTIES  _BACKTRACE_TRIPLES "/Users/arcop/code/git/libmysofa-wasm/CMakeLists.txt;107;add_test;/Users/arcop/code/git/libmysofa-wasm/CMakeLists.txt;0;")
add_test(fail-issue-173 "/Users/arcop/code/git/libmysofa-wasm/tests/notcrashed.sh" "/Users/arcop/code/git/libmysofa-wasm/tests/fail-issue-173")
set_tests_properties(fail-issue-173 PROPERTIES  _BACKTRACE_TRIPLES "/Users/arcop/code/git/libmysofa-wasm/CMakeLists.txt;107;add_test;/Users/arcop/code/git/libmysofa-wasm/CMakeLists.txt;0;")
add_test(CIPIC_subject_003_hrir_final "/Users/arcop/code/git/libmysofa-wasm/tests/compare.sh" "/Users/arcop/code/git/libmysofa-wasm/tests/CIPIC_subject_003_hrir_final")
set_tests_properties(CIPIC_subject_003_hrir_final PROPERTIES  _BACKTRACE_TRIPLES "/Users/arcop/code/git/libmysofa-wasm/CMakeLists.txt;110;add_test;/Users/arcop/code/git/libmysofa-wasm/CMakeLists.txt;0;")
add_test(FHK_HRIR_L2354 "/Users/arcop/code/git/libmysofa-wasm/tests/compare.sh" "/Users/arcop/code/git/libmysofa-wasm/tests/FHK_HRIR_L2354")
set_tests_properties(FHK_HRIR_L2354 PROPERTIES  _BACKTRACE_TRIPLES "/Users/arcop/code/git/libmysofa-wasm/CMakeLists.txt;112;add_test;/Users/arcop/code/git/libmysofa-wasm/CMakeLists.txt;0;")
add_test(LISTEN_1002_IRC_1002_C_HRIR "/Users/arcop/code/git/libmysofa-wasm/tests/compare.sh" "/Users/arcop/code/git/libmysofa-wasm/tests/LISTEN_1002_IRC_1002_C_HRIR")
set_tests_properties(LISTEN_1002_IRC_1002_C_HRIR PROPERTIES  _BACKTRACE_TRIPLES "/Users/arcop/code/git/libmysofa-wasm/CMakeLists.txt;113;add_test;/Users/arcop/code/git/libmysofa-wasm/CMakeLists.txt;0;")
add_test(Pulse "/Users/arcop/code/git/libmysofa-wasm/tests/compare.sh" "/Users/arcop/code/git/libmysofa-wasm/tests/Pulse")
set_tests_properties(Pulse PROPERTIES  _BACKTRACE_TRIPLES "/Users/arcop/code/git/libmysofa-wasm/CMakeLists.txt;115;add_test;/Users/arcop/code/git/libmysofa-wasm/CMakeLists.txt;0;")
add_test(Tester "/Users/arcop/code/git/libmysofa-wasm/tests/compare.sh" "/Users/arcop/code/git/libmysofa-wasm/tests/tester")
set_tests_properties(Tester PROPERTIES  _BACKTRACE_TRIPLES "/Users/arcop/code/git/libmysofa-wasm/CMakeLists.txt;116;add_test;/Users/arcop/code/git/libmysofa-wasm/CMakeLists.txt;0;")
add_test(TU-Berlin_QU_KEMAR_anechoic_radius_0.5_1_2_3_m "/Users/arcop/code/git/libmysofa-wasm/tests/compare.sh" "/Users/arcop/code/git/libmysofa-wasm/tests/TU-Berlin_QU_KEMAR_anechoic_radius_0.5_1_2_3_m")
set_tests_properties(TU-Berlin_QU_KEMAR_anechoic_radius_0.5_1_2_3_m PROPERTIES  _BACKTRACE_TRIPLES "/Users/arcop/code/git/libmysofa-wasm/CMakeLists.txt;117;add_test;/Users/arcop/code/git/libmysofa-wasm/CMakeLists.txt;0;")
add_test(TU-Berlin_QU_KEMAR_anechoic_radius_0.5m "/Users/arcop/code/git/libmysofa-wasm/tests/compare.sh" "/Users/arcop/code/git/libmysofa-wasm/tests/TU-Berlin_QU_KEMAR_anechoic_radius_0.5m")
set_tests_properties(TU-Berlin_QU_KEMAR_anechoic_radius_0.5m PROPERTIES  _BACKTRACE_TRIPLES "/Users/arcop/code/git/libmysofa-wasm/CMakeLists.txt;119;add_test;/Users/arcop/code/git/libmysofa-wasm/CMakeLists.txt;0;")
add_test(example_dummy_sofa48 "/Users/arcop/code/git/libmysofa-wasm/tests/compare.sh" "/Users/arcop/code/git/libmysofa-wasm/tests/example_dummy_sofa48")
set_tests_properties(example_dummy_sofa48 PROPERTIES  _BACKTRACE_TRIPLES "/Users/arcop/code/git/libmysofa-wasm/CMakeLists.txt;121;add_test;/Users/arcop/code/git/libmysofa-wasm/CMakeLists.txt;0;")
add_test(TestSOFA48_netcdf472 "/Users/arcop/code/git/libmysofa-wasm/tests/compare.sh" "/Users/arcop/code/git/libmysofa-wasm/tests/TestSOFA48_netcdf472")
set_tests_properties(TestSOFA48_netcdf472 PROPERTIES  _BACKTRACE_TRIPLES "/Users/arcop/code/git/libmysofa-wasm/CMakeLists.txt;123;add_test;/Users/arcop/code/git/libmysofa-wasm/CMakeLists.txt;0;")
add_test(example_dummy_sofa48_with_user_defined_variable "/Users/arcop/code/git/libmysofa-wasm/tests/compare.sh" "/Users/arcop/code/git/libmysofa-wasm/tests/example_dummy_sofa48_with_user_defined_variable")
set_tests_properties(example_dummy_sofa48_with_user_defined_variable PROPERTIES  _BACKTRACE_TRIPLES "/Users/arcop/code/git/libmysofa-wasm/CMakeLists.txt;125;add_test;/Users/arcop/code/git/libmysofa-wasm/CMakeLists.txt;0;")
subdirs("src")
